### ISSUE TITLE
Enhancement: Swipe Left and Right gesture to be able to be set with time constraints

### ISSUE THREAD

**Issue by flossokay** [MrMannWood/launcher#1]
I, as a user, would like to have my quick gestures to be able to be set via a time.  This would benefit the user as it would provide contextual shortcuts.

 Example: 

Up to noon: Swipe Left is Maps, Swipe Right is podcasts
Noon to 5pm: Swipe Left is Yahoo finance, Swipe Right is Robinhood
5pm to Morning: Swipe Left is Chrome, Swipe Right is Maps

**Comment by MrMannWood** [comment]
I like this idea, and will look into different ways of implementing it. It might take a bit though as I want to get the UX right.

Off the top of my head, I'm imagining a "profiles" system, that allows different gestures (and maybe widgets) based on time of day. This could be extended to location in the future, but I want to avoid sensitive permissions for as long as I can.

**Comment by MrMannWood** [comment]
Closing as "won't do." I still generally like the idea, but the greatly increased number of gestures as of 1.4.0 should make this moot.
