### ISSUE TITLE
[Feature Request]: Add the ability to use the launcher as an assistant app

### ISSUE THREAD

**Issue by darhma** [MrMannWood/launcher#10]
I discovered this app on f-droid and I must say that I liked it very much, congratulations. If it is not too complicated to implement, I would like to have the possibility to use the app as an assistant app (long tap on the home button or swipe from the lower corners) as as the main launcher I am very comfortable with kiss launcher but I find it convenient the gesture wheel, lately I was using pie launcher as an assistant app that has a similar function but has the defect of taking a few seconds to start while hex launcher is practically instantaneous. Thank you

**Comment by MrMannWood** [comment]
I like this idea, but won't be implementing it at this time. Enabling this to be an assistant requires me to add a whole heap of permissions (e.x. microphone) which I'm simply unwilling to do.
One of my big goals with Hex Launcher is to keep its permissions minimal. If enabling assistant-like integration didn't require them then I'd be all about this.

**Comment by darhma** [comment]
I have probably explained myself wrong or I am missing something (since I am not a developer and English is not my language), I do not think that enabling Hex Launcher as assistant app requires adding special permissions or at least this is what that I guess seeing other apps that can work as assistants but do not require special permissions such as:

https://github.com/markusfisch/PieLauncher
https://f-droid.org/packages/de.markusfisch.android.pielauncher/

https://github.com/scubajeff/Setter
(https://f-droid.org/packages/site.leos.setter/)

https://github.com/cvzi/ScreenshotTile
(https://f-droid.org/packages/com.github.cvzi.screenshottile/)

As I said I am not a developer so I could be wrong and in this case I agree that it is better to keep the Hex Launcher with minimal permissions. My idea was simply to have a way to quickly start the Hex Launcher in case it was not used as the default launcher not to turn it into google assistant 😉
