### ISSUE TITLE
[Feature request] swipe down gesture and cheat code

### ISSUE THREAD

**Issue by loic5032** [MrMannWood/launcher#11]
Hi! I love your launcher and have been using it for a while. I would like to make to feature suggestions. The first one would be a swipe down to open notitfications. The second would be a kind of cheat code (maybe just * or #) to see all apps on the home screen.

**Comment by MrMannWood** [comment]
As of 1.4.2, swiping straight down will open the notifications shade.

I'm considering adding a way to display all apps on the home screen

**Comment by MrMannWood** [comment]
As of 1.4.3, there will be an option to make searching "..." display all apps
