### ISSUE TITLE
[Feature Request] Daily new wallpaper

### ISSUE THREAD

**Issue by taboov** [MrMannWood/launcher#16]
I'm not sure how much it cost the privacy of the user to implement this feature, since hex launcher seems to be very privacy focused.
*It's been said.*

**As a user, I like my wallpaper background to be updated daily**

This feature is well-developed in [Olauncher](https://github.com/tanujnotes/Olauncher) app, if you like to take a look. If you set it on, it will update the wallpaper daily.

**Comment by MrMannWood** [comment]
I believe there are apps specifically for changing your wallpaper. I've never looked into it though.

My issue is that it would require either massively inflating the APK size (by adding a limited number to the APK itself) or else would require internet permissions.

I may someday add internet permissions, but it's still a long way off.
