### ISSUE TITLE
Enhancement: Swipe Left and Right gesture to be able to be set with location

### ISSUE THREAD

**Issue by flossokay** [MrMannWood/launcher#2]
This would be an enhancement on top of the time constraints one.

I, as a user, would like to be able to set my swipe right and left gestures with the context of location and time.

Example:
Morning/In house: Swipe left podcasts.  Swipe Right Email
Morning/Office: Swipe left: Chat.  Swipe Right: Work Email

**Comment by MrMannWood** [comment]
[Closing as duplicate.](https://github.com/MrMannWood/launcher/issues/1) As I stated in that task, I'm wary of sensitive permissions, at least for the time being. But I do agree that this would be very useful.
