### ISSUE TITLE
[Bug] “Open App When Last Option” feature has problem with an app's name with more than one word

### ISSUE THREAD

**Issue by hama73** [MrMannWood/launcher#22]
## Current Behavior
When an app's name is more than one word, it won't open it up until you type and get to the second word, even if there's no other matching name.
Example: If I want to open “Aurora Store” app I have to type `auroras` then it will open

## Expected Behavior
In my case, it should open “Aurora Store” after I typed `aur` because there isn't any other app that matches.

**Comment by MrMannWood** [comment]
This is a feature, not a bug. I understand the desire, but requiring that the name be an exact match prevents a significant number of other issues.
