### ISSUE TITLE
[Bug] Crash if you use a work profile

### ISSUE THREAD

**Issue by Joe-0237** [MrMannWood/launcher#24]
If any app is installed only in the work profile and not in the main profile, the launcher crashes on startup and therefore cannot be used at all if the user use work profiles.

Possibly related: if an app is installed on both the main and work profile the launcher launches the main profile installation regardless of which icon is selected by the user.

**Comment by MrMannWood** [comment]
Hopefully fixed by 1.4.6. I don't have a work profile so I cannot confirm.

**Comment by Joe-0237** [comment]
crash fixed, all else not
please see https://github.com/MrMannWood/launcher/issues/26
