### ISSUE TITLE
[FR] Need Digital Wellbeing Widget

### ISSUE THREAD

**Issue by ARBoyGo** [MrMannWood/launcher#30]
### **Why this feature is necessary**
Because we can track our screen time. 
In this launcher it's required because of its minimalist design approach. 

_Hope you bring this feature._

**Comment by adminvulcano** [comment]
Widget support in general would be very welcome. Widgets like calendar and weather reduce the need for opening apps, which I think this app is made for.

**Comment by adminvulcano** [comment]
Nevermind this feature request should be solved with #20. I think it can be closed.

**Comment by MrMannWood** [comment]
Closing as duplicate: https://github.com/MrMannWood/launcher/issues/20
