### ISSUE TITLE
[FR] Add a option to hide status bar.

### ISSUE THREAD

**Issue by ARBoyGo** [MrMannWood/launcher#31]
### **Why this feature is required?**
Because it actually give a fresh look.
No status bar and Navigation bar.
![Screenshot_2022-08-24-16-30-18-061_com mrmannwood hexlauncher](https://user-images.githubusercontent.com/69381592/186402379-3e276ea6-daac-4448-9350-fb12eb4eeb21.jpg)

This will be Cool. Hope you bring this.

**Comment by MrMannWood** [comment]
It is not possible to hide these permanently, and the ways to temporarily hide them make them re-appear with user interaction. Given that the point of a home screen is to be interacted with, I will not be implementing this feature.

Hopefully the changes for transparent status and navigation will work for you.
