### ISSUE TITLE
[FR] Ability to open more apps from the home screen

### ISSUE THREAD

**Issue by pogkythunder** [MrMannWood/launcher#36]
I recently discovered this launcher on F-Droid and I really like the concept. The only problem is that very few (6) apps are available to be opened easily. So I thought of a potential solution.

The launcher as is allows the user to long tap anywhere on the screen and a set of apps will pop up around the tap, no matter the position. A variation of this would be to allow configuring different locations for different sets of apps. 

For instance, I long tap on the lower right of the screen and I get to choose among my system tools. Then I long tap on the lower left part of my screen and I am presented with another set of apps, communication apps for example. Same for the other two quarters of the screen. That would allow for a total of 24 apps being launchable from the home screen instead of the current 6. Muscle memory should make getting used to that workflow easy.

What do you think?

**Comment by MrMannWood** [comment]
I'm considering different ways of having faster access to more apps, but I'm not planning on following this suggestion. I don't want users incentivized to reach far across their phone screens.
